name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
defaults:
  run:
    shell: bash --noprofile --norc -euxo pipefail {0}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: scripts/install_imagemagick_and_oxipng.sh

      - name: Restore npm cache if possible
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

      - name: Restore dprint cache if possible
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: ~/.cache/dprint
          key: ${{ runner.os }}-dprint-${{ hashFiles('dprint.jsonc') }}

      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c #v4.3.0

      - run: npm ci
      - run: npm run lint
      - run: npm run build
