name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
permissions:
  contents: write
defaults:
  run:
    shell: bash --noprofile --norc -euxo pipefail {0}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Validate version numbers
        run: |
          readonly tag="${GITHUB_REF#refs/tags/}"
          if ! [[ "$tag" =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
            echo 'Specified tag is not a valid SemVer.' >&2
            exit 1
          fi

          manifest_version="$(jq --raw-output '.version' 'manifest.json')"
          package_version="$(jq --raw-output '.version' 'package.json')"
          if ! [[ "$tag" == "$manifest_version" && "$tag" == "$package_version" ]]; then
            echo 'Version numbers should match.' >&2
            exit 1
          fi

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: scripts/install_imagemagick_and_oxipng.sh

      - name: Restore npm cache if possible
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      - run: |
          npm ci
          npm run build
      - name: Generate artifact attestation
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: |
            web-ext-artifacts/copy_markdown_link-*.*.*.zip

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          readonly tag="${GITHUB_REF#refs/tags/}"
          gh release create \
            "$tag" --title="$tag" \
            --fail-on-no-commits --generate-notes \
            web-ext-artifacts/copy_markdown_link-*.*.*.zip
